apt-get install nodejs-legacy
apt-get install node-express
apt install npm
npm install python-shell
npm install ws
npm install nodejs-websocket
npm install sleep
npm install multer
npm install passport
npm install connect-flash
npm install morgan
npm install cookie-parser
npm install body-parser
npm install express-session
npm install sqlite3
npm install connect-busboy
npm install passport-local
npm install bcrypt-nodejs
npm install line-reader
npm install csv-parse
npm install ejs
npm install express
npm install append-field
